from enum import IntEnum


class ActionMode(IntEnum):
    KEEP = 0
    STOP = 1
    PROCEED = 2
    LANE_CHANGE_LEFT = 3
    LANE_CHANGE_RIGHT = 4
    MERGE = 5
    NUDGE_LEFT = 6
    NUDGE_RIGHT = 7
    CREEP = 8


class EvidenceType(IntEnum):
    DYNAMIC_AGENT = 0
    CONFLICT_POINT = 1
    GAP = 2
    MAP_RULE = 3
    LOW_TTC_RISK = 4
    PADDING = 5


class MapRuleCode(IntEnum):
    NONE = 0
    STOP_LINE = 1
    CROSSWALK = 2
    LANE_BOUNDARY = 3
    TRAFFIC_LIGHT_RED = 4
    DRIVABLE_AREA = 5
    SPEED_LIMIT = 6
    ROUTE_DEVIATION = 7
    INTERSECTION = 8
    LANE_CONNECTOR = 9


class QueryIndex(IntEnum):
    MIN_DISTANCE = 0
    MIN_DISTANCE_TIME = 1
    INTERSECTS = 2
    OVERLAP_AREA_SUM = 3
    OVERLAP_AREA_MAX = 4
    EGO_ARRIVAL_TIME = 5
    HEADING_DIFFERENCE = 6
    ROUTE_DISTANCE = 7
    UNIT_BEFORE_AFTER_EGO = 8
    ARRIVAL_TIME_DIFFERENCE = 9
    RELATIVE_SPEED = 10
    RELATIVE_HEADING = 11
    EGO_PASSES_BEFORE = 12
    AGENT_PASSES_BEFORE = 13
    TTC = 14
    FOOTPRINT_OVERLAP_MAX = 15
    GAP_FRONT_DISTANCE = 16
    GAP_REAR_DISTANCE_OR_STOP_CROSS = 17
    GAP_REAR_REL_SPEED_OR_CROSSWALK = 18
    MERGE_TIME_OR_DRIVABLE = 19
    GAP_APPLIES_OR_LANE_BOUNDARY = 20
    SPEED_LIMIT_VIOLATION = 21
    ROUTE_DEVIATION = 22
    VALID = 23


ACTION_STATE_DIM = 6
ACTION_META_DIM = 8
EGO_DIM = 9  # [x,y,yaw,vx,vy,ax,ay,yaw_rate,speed] in ego-centric coordinates
AGENT_DIM = 8  # [x,y,yaw,vx,vy,length,width,type_code]
MAP_DIM = 4
EVIDENCE_DIM = 32
QUERY_DIM = 24
